filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
- https://github.com/ghostery/broken-page-reports/issues/426 ✅ works on latest autoconsent, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/52 ✅ works on latest autoconsent, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/269 📝 doesn't work on latest autoconsent, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/203 📝 doesn't work on latest autoconsent, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/193 📝 doesn't work on latest autoconsent, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/171 ✅ works on latest autoconsent, fix pushed
- `glowstery.com`
- `tn.com.ar`
=> Daily filter fixes

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
- https://github.com/ghostery/broken-page-reports/issues/284 ✅ latest autoconsent should handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/299 📝 doesn't work on latest autoconsent, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/309 📝 fix pushed
- https://github.com/ghostery/broken-page-reports/issues/277 📝 doesn't work on latest autoconsent, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/192 ✅ latest autoconsent should handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/337#issuecomment-1882784564 ❌ Removed duplicate
- https://github.com/ghostery/broken-page-reports/issues/401 ❌ only autoconsent pr created
=> Daily filter fixes (Jan 10)

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
- https://github.com/ghostery/broken-page-reports/issues/431 ✅ latest autoconsent handles, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/306 📝 latest autoconsent doesn't handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/295 📝 latest autoconsent doesn't handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/305 📝 latest autoconsent doesn't handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/274 📝 latest autoconsent doesn't handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/287 📝 latest autoconsent doesn't handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/382 📝 latest autoconsent doesn't handle, fix pushed
- …
=> Daily filter fixes (Jan 11 to 12)

filters/cookies.txt, filters/fixes.txt
- https://github.com/ghostery/broken-page-reports/issues/437 📝 latest autoconsent doesn't handle, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/264 📝 latest autoconsent doesn't handle (opt-out by default), fix pushed
- https://github.com/ghostery/broken-page-reports/issues/243 ✅ safari specific, fix pushed
- https://github.com/ghostery/broken-page-reports/issues/190 ✅ latest autoconsent does handle, fix pushed
=> Daily filter fixes (Jan 16)

filters/cookies.txt, filters/fixes.txt
- https://github.com/ghostery/broken-page-reports/issues/273 ✅ fix pushed
- https://github.com/ghostery/broken-page-reports/issues/442 ✅ fix pushed
- https://github.com/ghostery/broken-page-reports/issues/441 📝 latest autoconsent doesn't handle, fix pushed
=> Daily filter fixes (Jan 17)

filters/fixes.txt
refs https://github.com/ghostery/broken-page-reports/issues/446
=> Fixes consentmanager.net

assets/index.html
The output html haven't been updated.
=> chore: fix typo

filters/fixes.txt
refs https://github.com/ghostery/broken-page-reports/issues/457
=> Unbreak YouTube consent dialog

filters/fixes.txt
- https://github.com/ghostery/broken-page-reports/issues/454 ✅ fix pushed
- https://github.com/ghostery/broken-page-reports/issues/460 ✅ fix pushed
=> Daily filter fixes (Jan 23~24)

filters/cookies.txt
refs https://github.com/ghostery/broken-page-reports/issues/465
=> cookies: dmarcian.com

filters/cookies.txt
refs https://github.com/ghostery/broken-page-reports/issues/469
=> cookie: mi.com

filters/fixes.txt
refs https://github.com/ghostery/broken-page-reports/issues/479
=> fix(breakage): bearingarms.com~piano.io

filters/fixes.txt
=> fix(breakage): hm.com

.github/ISSUE_TEMPLATE/broken-page.md, filters/annoyances.txt
To handle the general annoyances in websites, annoyance list is required for broken-page-reports. Also, this includes update on issue template.
refs https://github.com/ghostery/broken-page-reports/issues/443
=> feat: annoyances

filters/fixes.txt
- #491 , anti-adblock
- #493 , ad
=> Daily filter fixes (Feb 6)

filters/annoyances.txt, filters/fixes.txt
- #492 , anti-adblock
- #495 , anti-adblock, merged multiple `.fc-ab-root` rules into one
- https://github.com/ghostery/broken-page-reports/issues/443#issue-2085727117 , annoyances
- #499 , anti-adblock, `.fc-ab-root`
- #497 , ad
=> Daily filter fixes (Feb 7)

filters/fixes.txt
- #501 , autoconsent doesn't handle
- #502 , fixed by removing dialog overlay
=> Daily filter fixes (Feb 9)

filters/fixes.txt
- #506, #507, #508 are related to `.fc-ab-root`
=> Daily filter fixes (Feb 12)

filters/fixes.txt
=> fix: disable -cookie-banner-$~image globally

filters/cookies.txt, filters/fixes.txt
```
definitions.net,synonyms.com,compsmag.com
```
**admiral domains**
```
whimsicalcanyon.com
```
- This needs to be addressed in TrackerDB.
=> Daily filter fixes (Feb 20)

.github/workflows/release.yaml, .github/workflows/test.yaml
=> fix(ci): migrate to mise-action v2

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
Importants
- UserCentrics hotfix
=> Filter fixes

filters/cookies.txt, filters/fixes.txt
This only contains Ghostery v8 fixes.
=> Daily filter fixes (Mar 7) (v8)

filters/fixes.txt
- https://github.com/ghostery/broken-page-reports/issues/580
=> Filter fixes (Mar 18)

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
For `centraalbeheer.nl`, it requires to query elements inside `iframe`. Investigating on autoconsent.
=> Filter fixes (Mar 22)

filters/fixes.txt
refs https://github.com/ghostery/broken-page-reports/issues/622
=> fix: recaptcha.net

filters/fixes.txt
refs https://github.com/ghostery/broken-page-reports/issues/625
refs https://github.com/duckduckgo/autoconsent/pull/435
=> fix: instagram.com

filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/639
=> Unbreak morgenpost.de

filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/647
=> Unbreak derwesten.de

filters/fixes.txt
Do not block all "/consent-tracking-api.js" request, since it includesconsent managers.
refs https://github.com/ghostery/broken-page-reports/issues/650
=> Unbreak Pandectes

filters/autoconsent-compatibility.txt
=> autoconsent-compat: passenger-clothing.com

filters/fixes.txt
refs https://github.com/easylist/easylist/pull/19348
=> fix: wwwapps.ups.com

filters/fixes.txt
refs https://github.com/ghostery/broken-page-reports/issues/711
=> fix: tescobank.com

filters/cookies.txt
Fixes https://github.com/ghostery/ghostery-extension/issues/1702
=> kabel24.nl

filters/autoconsent-compatibility.txt
refs https://github.com/ghostery/broken-page-reports/issues/650
=> Do not block pandectes overlay window

filters/autoconsent-compatibility.txt
blocks https://github.com/ghostery/ghostery-extension/pull/1721#pullrequestreview-2160748062
=> Allow Usercentrics

filters/autoconsent-compatibility.txt
refs https://github.com/ghostery/broken-page-reports/issues/806
=> Show TrustArc Cookie Preference link on oracle.com

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
fixes #808
fixes #809
fixes #813
fixes #814
fixes #815
fixes #816
fixes #819
fixes #760
fixes #795
fixes #796
=> Filter fixes (Aug 28-29)

filters/cookies.txt, filters/fixes.txt
fixes #800
fixes #820
fixes #195
fixes #161
=> Filter fixes (2 Sep)

filters/cookies.txt, filters/fixes.txt
fixes #823
fixes #805
fixes #825
fixes #826
refs https://github.com/ghostery/broken-page-reports/issues/743#issuecomment-2330189557
=> Filter fixes (Sep 6)

filters/cookies.txt, filters/fixes.txt
fixes #828
fixes #410 
fixes https://github.com/ghostery/broken-page-reports/issues/830
fixes https://github.com/ghostery/broken-page-reports/issues/832
=> Filter fixes (Sep 9)

filters/fixes.txt
=> fix: address possible scriptlet conflicts

filters/annoyances.txt, filters/autoconsent-compatibility.txt, filters/fixes.txt
refs #847
refs #851
fixes https://github.com/ghostery/broken-page-reports/issues/849
refs #848
refs https://github.com/ghostery/broken-page-reports/issues/842
refs https://github.com/ghostery/broken-page-reports/issues/840
=> Filter fixes (Sep 18)

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/194
fixes https://github.com/ghostery/broken-page-reports/issues/249
fixes https://github.com/ghostery/broken-page-reports/issues/250
refs https://github.com/ghostery/broken-page-reports/issues/203
=> fix: filters (sep 25)

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
refs #863
fixes #265 
fixes #264
refs https://github.com/ghostery/broken-page-reports/issues/828
fixes https://github.com/ghostery/broken-page-reports/issues/290
=> fix(filters): Sep 26

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/868
fixes https://github.com/ghostery/broken-page-reports/issues/866
refs https://github.com/easylist/easylist/pull/20051
refs https://github.com/ghostery/broken-page-reports/issues/843
refs https://github.com/ghostery/broken-page-reports/issues/545
refs https://github.com/ghostery/broken-page-reports/issues/549
fixes https://github.com/ghostery/broken-page-reports/issues/320
refs https://github.com/ghostery/broken-page-reports/issues/857
=> fix(filters): Sep 30

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/871
refs https://github.com/ghostery/broken-page-reports/issues/870
fixes https://github.com/ghostery/broken-page-reports/issues/841
fixes https://github.com/ghostery/broken-page-reports/issues/404
=> fix(filters): Oct 1

filters/annoyances.txt, filters/cookies.txt, filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/898
fixes https://github.com/ghostery/broken-page-reports/issues/897
fixes https://github.com/ghostery/broken-page-reports/issues/849
=> fix(filters): Oct 14

.github/ISSUE_TEMPLATE/general.yml, .github/advanced-issue-labeler.yml
- Add platform selection
- Drop zendesk shortcut
=> docs: update issue template

filters/fixes.txt
=> fix(filters): Oct 15

filters/cookies.txt, filters/fixes.txt
fixes #906
refs #904
fixes #899
=> fix(filters): Oct 17

filters/autoconsent-compatibility.txt, filters/fixes.txt
refs https://github.com/ghostery/broken-page-reports/issues/899
=> fix(autoconsent-compat): citibank.pl

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes https://github.com/ghostery/broken-page-reports/issues/918
fixes https://github.com/ghostery/broken-page-reports/issues/917
fixes https://github.com/ghostery/broken-page-reports/issues/914
fixes https://github.com/ghostery/broken-page-reports/issues/886
fixes https://github.com/ghostery/broken-page-reports/issues/926
fixes https://github.com/ghostery/broken-page-reports/issues/929
=> fix(filters): Oct 21

filters/autoconsent-compatibility.txt, filters/fixes.txt, filters/privacy.txt
fixes https://github.com/ghostery/broken-page-reports/issues/938
fixes https://github.com/ghostery/broken-page-reports/issues/935
fixes https://github.com/ghostery/broken-page-reports/issues/953
fixes https://github.com/ghostery/broken-page-reports/issues/952
refs https://github.com/ghostery/broken-page-reports/issues/951
refs https://github.com/ghostery/broken-page-reports/issues/949
=> fix(filters): Oct 29

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/963
fixes https://github.com/ghostery/broken-page-reports/issues/961
fixes https://github.com/ghostery/broken-page-reports/issues/958
fixes https://github.com/ghostery/broken-page-reports/issues/957
fixes https://github.com/ghostery/broken-page-reports/issues/956
fixes https://github.com/ghostery/broken-page-reports/issues/954
=> fix(filters): Nov 13

filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/970
fixes https://github.com/ghostery/broken-page-reports/issues/1004
=> fix(filters): Dec 3

filters/annoyances.txt, filters/autoconsent-compatibility.txt, filters/cookies.txt
fixes #1013
fixes #1008 
refs #1007
=> fix(filters): Dec 6

filters/autoconsent-compatibility.txt, filters/fixes.txt, filters/privacy.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1019
fixes https://github.com/ghostery/broken-page-reports/issues/1000
refs https://github.com/ghostery/broken-page-reports/issues/990
=> fix(filters): Dec 11

filters/fixes.txt
reported to easylist https://github.com/easylist/easylist/issues/20825
=> Fix filen.io

filters/autoconsent-compatibility.txt
refs https://github.com/ghostery/broken-page-reports/issues/267
https://github.com/ghostery/broken-page-reports/issues/267#issuecomment-2545385660
=> Fix: consent.youtube.com

filters/cookies.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1051
This is a temporal fix until the investigation completes.
```
! https://github.com/ghostery/broken-page-reports/issues/1051
!#if env_firefox
bestbuy.ca###onetrust-consent-sdk
!#endif
```
=> fix(cookie): bestbuy.ca

filters/cookies.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1053
```
! https://github.com/ghostery/broken-page-reports/issues/1053
coastcapitalsavings.com##div.cookies-disclaimer
```
=> fix(cookie): coastcapitalsavings.com

filters/autoconsent-compatibility.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1065
=> fix(autoconsent-compat): privacyportaltrial-cdn.onetrust.com

filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1060
```
! https://github.com/ghostery/broken-page-reports/issues/1060
! >>> url=https://sdk.privacy-center.org/sdk/326c6bd191c11b5e1333a693feb3a6027adc6492/modern/sdk.326c6bd191c11b5e1333a693feb3a6027adc6492.js
! >>> source=https://cinema-series.orange.fr/series/toutes-les-actus/une-fille-m-a-tout-a-coup-traite-de-l-interprete-de-nellie-oleson-la-petite-maison-dans-la-prairie-etait-prise-a-partie-par-le-public-de-la-serie-CNT000002gSIq2.html
! ... type=script
@@||sdk.privacy-center.org^$script,domain=orange.fr
! >>> url=https://tags.tiqcdn.com/utag/orange/dnu/prod/utag.440.js?utv=ut4.39.202408060909
! ... source=https://cinema-series.orange.fr/series/toutes-les-actus/une-fille-m-a-tout-a-coup-traite-de-l-interprete-de-nellie-ole …
```
=> fix: orange.fr

filters/privacy.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1063
=> fix(privacy): allthekingz.com

filters/fixes.txt
fixes #1061
fixes #1074
fixes #1079
Please, do testing keeping experimental filters are on.
```
@@||applovin.com^$1p
tvtv.us##+js(aopr, eval)
bing.com##li.b_algo:has(div[role="contentinfo"]>p>strong)
```
=> fix(filters): Jan 14

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1081
fixes https://github.com/ghostery/broken-page-reports/issues/1048 nsfw
fixes https://github.com/ghostery/broken-page-reports/issues/1046
fixes https://github.com/ghostery/broken-page-reports/issues/1077
fixes https://github.com/ghostery/broken-page-reports/issues/968 nsfw
refs https://github.com/ghostery/broken-page-reports/issues/1065 requires investigation on adblocker-library (see https://github.com/ghostery/broken-page-reports/pull/1082/commits/94d5b1ecdbc08e536fbd6871ff8751cf6cee2171)
=> fix(filters): Jan 15

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1087
fixes #408
fixes #1078
fixes #664 (potential privacy-risk)
fixes #798 (autoconsent "hide" action is self-blocking; see commit description)
fixes #811
=> fix(filters): Jan 20

filters/cookies.txt, filters/experimental.txt, filters/fixes.txt
refs #941 move to stable
refs #1074 move to stable
fixes #1091
refs #410 (former issue of #1091)
fixes #1090 (also depends on https://github.com/yous/YousList/issues/584)
fixes #1073
=> fix(filters): Jan 21

filters/cookies.txt, filters/experimental.txt, filters/fixes.txt
fixes #1072
fixes #1047
refs #1061
refs #877
fixes #865
fixes #1091
=> fix(filters): Jan 22

filters/fixes.txt, filters/privacy.txt
refs #1096
fixes #1098
refs #904
fixes #1100
=> fix(filters): Jan 23

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1111
fixes ghostery#1110
fixes #1109
fixes #1105
=> fix(filters): Jan 27

filters/autoconsent-compatibility.txt, filters/experimental.txt, filters/fixes.txt
fixes #1119 
fixes #1115 
fixes #1118
=> fix(filters): Jan 28

filters/cookies.txt, filters/experimental.txt, filters/fixes.txt
fixes ghostery#1121
fixes ghostery#1119
fixes ghostery#743
fixes ghostery#1127
=> fix(filters): Jan 30-31

filters/fixes.txt, filters/privacy.txt
=> fix(filters): Feb 4

filters/fixes.txt
fixes https://github.com/ghostery/ghostery-extension/issues/2236
=> chore: disable filter on Firefox

filters/cookies.txt, filters/experimental.txt, filters/fixes.txt, filters/privacy.txt
fixes #1180
fixes #1179
fixes #1176
fixes #1183
fixes #1173
fixes #1172
fixes #1171
fixes #1170
fixes #1168
=> fix(filters): Feb 24

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/experimental.txt, filters/fixes.txt
fixes #1187
fixes ghostery#1186
fixes ghostery#1184
fixes ghostery#1193
fixes ghostery#1192
fixes ghostery#1190
fixes ghostery#1188
fixes ghostery#1166
fixes ghostery#1162
fixes ghostery#1160
fixes ghostery#1158
=> fix(filters): Feb 25

filters/cookies.txt, filters/fixes.txt
fixes #1198
fixes ghostery#1177
=> fix(filters): Feb 28

filters/cookies.txt, filters/fixes.txt
fixes #1235
fixes #1234
fixes #1233
fixes #1232
fixes #1236
=> fix(filters): Mar 7

filters/cookies.txt, filters/fixes.txt
fixes #1246
fixes ghostery#1243
=> fix(filters): Mar 12

filters/fixes.txt
=> fix: economictimes.indiatimes.com

filters/cookies.txt, filters/fixes.txt
fixes ghostery#1251
fixes ghostery#1252
fixes ghostery#1026
=> fix(filters): Mar 13

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1260
fixes ghostery#1264
fixes ghostery#1265
fixes ghostery#1263
fixes ghostery#1262
=> fix(filters): Mar 19

filters/annoyances.txt, filters/cookies.txt, filters/fixes.txt
fixes #1249
fixes #1257
fixes #1258
fixes #1268
fixes #1259 
fixes #1269 
fixes #1225
=> fix(filters): Mar 20

filters/annoyances.txt, filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
refs #1141
fixes #1283
fixes #1284
fixes #1285
fixes #1287
refs #1262
refs #1217
refs #1217
refs #1217
refs https://github.com/ghostery/broken-page-reports/issues/154
refs https://github.com/ghostery/broken-page-reports/issues/226
refs https://github.com/ghostery/broken-page-reports/issues/270
refs https://github.com/ghostery/broken-page-reports/issues/274
refs https://github.com/ghostery/broken-page-reports/issues/320
refs https://github.com/ghostery/broken-page-reports/issues/322
refs https://github.com/ghostery/broken-page-reports/issues/334
refs https://github.com/ghostery/broken-page-reports/issues/335
refs https://github.com/ghostery/broken-page-reports/issues/351
refs https://github.com/ghostery/broken-page-reports/issues/389
refs …
=> fix(filters): Mar 31

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt
fixes #1294
fixes #1257 
fixes #1295 
fixes #1065
fixes ghostery#743
=> fix(filters): Apr 6

filters/experimental.txt, filters/fixes.txt
=> fix(filters): Apr 7

filters/fixes.txt
fixes #1302
fixes #1301
fixes #1300
fixes #1299
=> fix: focus.de

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1002
fixes #1327 
fixes #1326
fixes #1325 
fixes #1324 
fixes #1323 
fixes #1321
=> fix(filters): Apr 14

filters/cookies.txt, filters/fixes.txt
fixes #1341
fixes #1342
fixes #1340
fixes #1339
fixes #1337
fixes #1336
=> fix(filters): Apr 23

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1369
fixes #1368
fixes #1367
fixes #1292
fixes #1364
fixes #1363
fixes #1362
fixes #1361
fixes #1357
=> fix(filters): May 5

filters/fixes.txt
fixes #1255
This PR was created separately to add verbosity.
=> fix: segment.com

filters/privacy.txt
=> fix(filters): May 12

filters/fixes.txt, filters/privacy.txt
fixes #942
fixes #1420
fixes #1327
=> fix(filters): Jun 4

filters/privacy.txt
=> fix(privacy): sflix.to

filters/cookies.txt
=> fix(cookie): att.com

filters/annoyances.txt, filters/cookies.txt, filters/experimental.txt, filters/fixes.txt, filters/privacy.txt
refs https://github.com/uBlockOrigin/uAssets/issues/26299
refs #1008
refs #892 
refs #849
refs #491
refs #493
refs #492
refs #753
fixes #731
refs #811
refs #1220
refs #1264
refs #1262
refs #1327
refs #1353
refs #1308
refs #1327
refs #949
refs #669
refs #815
refs #814
refs #670
refs #720
refs #710
fixes #725
refs #760
refs #830
refs #953
refs #957
refs #983
fixes #1386
refs #998
refs #1079
fixes #1048
fixes #1078
refs #1074
refs #1149
fixes #1235
refs #1265
fixes #1269
fixes #1225
fixes #1285
refs #1284
refs #1302
refs #1301
refs #1300
refs #893
refs #1369
fixes #1150
=> fix(filters): Jun 30

filters/fixes.txt
=> fix: watson.ch

filters/fixes.txt, filters/privacy.txt
=> fix(filters): Jul 9

filters/annoyances.txt, filters/fixes.txt, filters/privacy.txt
fixes #1515
fixes #1513
refs #1487
fixes #1468
=> fix(filters): Jul 17

filters/autoconsent-compatibility.txt, test/filters.test.ts
fixes https://github.com/ghostery/broken-page-reports/issues/1524
=> Autoconsent compatibility: borlabs

filters/fixes.txt, filters/privacy.txt
=> fix(filters): 8 Aug

.github/ISSUE_TEMPLATE/general.yml
New form simplifies the reporting scheme by:
- Drop the platform field (merged into browsers with additional details)
- Simplify the problem specification into behavioral definitions
This is the first try to simplify to test the simplified user reporting.
=> docs: simplify the form

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1563
fixes #1560
fixes #1562
fixes #1561
fixes #1557
fixes #1556
fixes #1548
fixes #1579
fixes #1578
fixes #1577
fixes #1558
fixes #1556
fixes #1555
fixes #1550
fixes #1549
fixes #1559
=> fix(filters): 14 Aug

.tool-versions, deno.json, deno.lock
=> ci: update dependencies

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1591
fixes #1587
fixes #1593
fixes #1592
fixes #1590
refs #1589
=> fix(filters): 15 Aug

filters/fixes.txt
=> fix: linux-magazin.de

filters/privacy.txt
=> fix(privacy): piptaucmie.com, ticdmgrd.com

filters/fixes.txt
=> fix: cuevana3.rs

filters/autoconsent-compatibility.txt
=> fix(autoconsent-compat): tise-master.eu

filters/fixes.txt
=> fix: plantguides.net, leboncoin.fr

filters/cookies.txt
The filter argument should be dynamic.
fixes #1660
=> fix: eset.com

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1674
fixes #1673
fixes #1672
fixes #1671
fixes #1670
fixes #1669
fixes #1630
fixes #1632
fixes #1631
fixes #769
=> fix(filters): 2 Sep

filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1695
fixes #1697
fixes #1694
fixes #1532
fixes #1692
fixes #1477
fixes #1690
fixes #1688
refs #1661
fixes #1696
fixes #1693
fixes #1477
fixes #1690
=> fix(filters): 4 Aug

filters/annoyances.txt, filters/autoconsent-compatibility.txt, filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1684
fixes #1443
fixes #1682
fixes #1681
fixes #937
fixes #945
fixes #950
fixes #857
fixes #851
fixes #1218
fixes #1679
fixes #1383
fixes #1686
fixes #1683
fixes #1680
fixes #933
fixes #947
fixes #967
refs #969
fixes #1540
fixes #1538
refs #1631 el dup, dead
refs #1630 el dup, alive
refs #1696 el dup, alive
refs #1693 el dup, alive
refs #1477 el dup, alive
refs #1690 el dup, alive
refs #1583 el dup, alive
refs #1603 el dup, alive
refs #1640 el dup, dead
refs #1645 el dup, alive
refs #1390 el dup, dead
refs #1476 el dup, alive
refs #1593 el dup, alive
refs #1601 optimise
refs #1672 optimise
fixes #1385
fixes #1546
fixes #1531
=> fix(filters): 5 Sep

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes #1707
fixes #1710
fixes #1736
fixes #1734
fixes #1472
fixes #1706
fixes #1720
fixes #1735
=> fix(filters): 15 Sep

filters/fixes.txt
=> fix: spiegel.de

filters/fixes.txt, filters/privacy.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1806
fixes https://github.com/ghostery/broken-page-reports/issues/1805
fixes https://github.com/ghostery/broken-page-reports/issues/1804
refs https://github.com/ghostery/broken-page-reports/issues/1342
refs https://github.com/ghostery/broken-page-reports/issues/1688
refs https://github.com/ghostery/broken-page-reports/issues/1383
fixes https://github.com/ghostery/broken-page-reports/issues/1803
fixes https://github.com/ghostery/broken-page-reports/issues/1783
fixes https://github.com/ghostery/broken-page-reports/issues/1799
fixes https://github.com/ghostery/broken-page-reports/issues/1798
=> fix(filters): 29 Sep

filters/cookies.txt, filters/fixes.txt, filters/privacy.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1832
fixes https://github.com/ghostery/broken-page-reports/issues/1833
fixes https://github.com/ghostery/broken-page-reports/issues/1831
refs https://github.com/ghostery/broken-page-reports/issues/1830
fixes https://github.com/ghostery/broken-page-reports/issues/1829
fixes https://github.com/ghostery/broken-page-reports/issues/1828
fixes https://github.com/ghostery/broken-page-reports/issues/1825
fixes https://github.com/ghostery/broken-page-reports/issues/1824
fixes https://github.com/ghostery/broken-page-reports/issues/1823
=> fix(filters): 1 Oct

filters/cookies.txt, filters/fixes.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1766
fixes https://github.com/ghostery/broken-page-reports/issues/1809
fixes https://github.com/ghostery/broken-page-reports/issues/1763
=> fix(filters): 2 Oct

filters/privacy.txt
Removes easylist duplicates (includes 1 regional filter [de] duplicates) and dead domains
refs #1325
refs #1321
refs #1513
refs #1600
refs #1620
refs #1644
refs #1630
refs #1696
refs #1538
refs #1716
refs #1706
refs #1704
refs #1793
refs #1782
refs #1773
refs #1772
refs #1771
refs #1825
refs #1824
refs #1823
=> chore(cleanup): 3 Oct
